### ISSUE TITLE
Clarification suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/mathml_formatter#4]
**On the HTML page:**
- Specify which file to upload for clarity
- Offer an example of a variable (e.g. deductibles v)
- Distinguish the difference between variable and function (perhaps by giving an example of a function)
- Elaborate the difference between m and c (perhaps with an example)
- Offer an example of a (from what I understand a is the same as v, except it is just an acronym. Is this still necessary?)
- Move the "It may be helpful to use in conjunction with the vba script to extract mathml in a Word document, and the general Dreamweaver paste formatting" sentence to the top of the page
- Should probably also move "It assumes proper source formatting (in Dreamweaver, Edit -> Code -> Apply Source Formatting) and consistent space encoding." to the top if this script relies on source formatting

**In the readme:**
- Clarify in the HTML page where the "Variable list formatting" is located
- Reword "This is find if a multicharacter variable is multiplied by another variable."
- Clarify in the HTML page where the "Summation formatting" option is located
- Give a visual example of Summation formatting

**On the get_math HTML page:**
- Specify which file to upload for clarity

**Comment by hughdingb58** [comment]
Went through and implemented most of these.
